/obj/machinery/vending/killbitches
	name = "\improper Atire-Putas"
	desc = "For when you really need to <b>KILL SOME BITHCES.</b>"
	icon_state = "killbitches"
	icon = 'modular_septic/icons/obj/vending.dmi'
	product_slogans = "Vai se foder porra!;GTA San Andreas crackeado SAMP sem virus!;Cria do pinheiro!"
	product_ads = "Mata-mata mundo louco!;Tudo 2!;Meu pau tá duro!"
	vend_reply = "Come back when you need more dead children!"
	panel_type = "panel17"
	default_price = 0
	products = list(
		/obj/item/food/soup/monkeysdelight = 666,
		/obj/item/reagent_containers/syringe/copium = 20,
		/obj/item/clothing/under/stray = 20,
		/obj/item/clothing/shoes/jackboots = 20,
		/obj/item/clothing/gloves/fingerless = 20,
		/obj/item/clothing/suit/armor/vest/alt/heavy = 10,
		/obj/item/clothing/suit/armor/vest/alt/medium = 10,
		/obj/item/clothing/head/helmet/heavy = 10,
		/obj/item/clothing/head/helmet/medium = 10,
		/obj/item/clothing/mask/gas/ordinator/slaughter = 20,
		/obj/item/storage/belt/military = 20,
		/obj/item/gun/ballistic/automatic/pistol/m1911 = 10,
		/obj/item/gun/ballistic/automatic/pistol/combatmaster = 3,
		/obj/item/gun/ballistic/revolver = 2,
		/obj/item/gun/ballistic/revolver/remis/nova = 15,
		/obj/item/ammo_casing/a357 = 65,
		/obj/item/ammo_casing/c38 = 120,
		/obj/item/ammo_box/magazine/combatmaster9mm = 69,
		/obj/item/ammo_box/magazine/m45 = 40,
		/obj/item/gun/ballistic/shotgun/automatic/combat = 5,
		/obj/item/ammo_casing/shotgun/ap = 1, //Better make it count, puta!
		/obj/item/ammo_casing/shotgun/buckshot = 569,
		/obj/item/ammo_casing/shotgun = 420,
		/obj/item/suppressor = 15,
		/obj/item/flashlight/seclite = 15,
		/obj/item/knife/kitchen = 2, //two of them
		/obj/item/melee/truncheon/black = 20,
		/obj/item/claymore = 2,
		/obj/item/gun/ballistic/automatic/remis/winter = 5,
		/obj/item/gun/ballistic/automatic/remis/abyss = 5,
		/obj/item/gun/ballistic/automatic/remis/g11 = 6,
		/obj/item/gun/ballistic/automatic/remis/steyr = 1,
		/obj/item/gun/ballistic/automatic/remis/svd = 1,
		/obj/item/ammo_box/magazine/a762svd = 4,
		/obj/item/ammo_box/magazine/a556steyr = 4,
		/obj/item/ammo_box/magazine/a49234g11 = 20,
		/obj/item/ammo_box/magazine/a54539abyss = 18,
		/obj/item/ammo_box/magazine/a762winter = 13,
		/obj/item/gun/ballistic/automatic/remis/smg/bastardo = 8,
		/obj/item/gun/ballistic/automatic/remis/smg/solitario = 20,
		/obj/item/gun/ballistic/automatic/remis/smg/thump = 5,
		/obj/item/ammo_box/magazine/thump45 = 20,
		/obj/item/ammo_box/magazine/hksmg22lr = 40,
		/obj/item/ammo_box/magazine/bastardo9mm = 25,
		/obj/item/grenade/frag = 3, //devious lick

	)
